### ISSUE TITLE
HTTP 403 forbidden on request to live scores URL

### ISSUE THREAD

**Issue by kaydarla** [psibi/cricbuzz#4]
```pytb
>>> match = cric.getXml()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cricbuzz.py", line 14, in getXml
    f = urllib2.urlopen("http://synd.cricbuzz.com/j2me/1.0/livematches.xml")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

How about adding a "User-Agent" header to the HTTP request?

```py
request = urllib2.Request("http://synd.cricbuzz.com/j2me/1.0/livematches.xml",
            headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8"})
f = urllib2.urlopen(request)
```

**Comment by psibi** [comment]
Can you send a PR ?

**Comment by kaydarla** [comment]
Yes, I can send in a PR. You could suggest a generic `User-Agent` string to be inserted in the request.
