### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by YashCS90** [psibi/cricbuzz#7]
C:\Python26>python` cricbuzz.py
Traceback (most recent call last):
  File "cricbuzz.py", line 156, in <module>
    match = cric.getXml()
  File "cricbuzz.py", line 16, in getXml
    f = urllib2.urlopen(r)
  File "C:\Python26\lib\urllib2.py", line 124, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python26\lib\urllib2.py", line 383, in open
    response = self._open(req, data)
  File "C:\Python26\lib\urllib2.py", line 401, in _open
    '_open', req)
  File "C:\Python26\lib\urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "C:\Python26\lib\urllib2.py", line 1130, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python26\lib\urllib2.py", line 1105, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 10060] A connection attempt failed becau
se the connected party did not properly respond after a period of time, or estab
lished connection failed because connected host has failed to respond>

**Comment by psibi** [comment]
@YashCS90 I can accept a PR for the fix.

**Comment by saltperfect** [comment]
It is a connection time out problem. Please check you connection.

**Comment by psibi** [comment]
As @Saltperfect says, it's a connection issue. Closing this issue, please re-open if you disagree.
